### ISSUE TITLE
Add parallax background layer 1 (grassy things) 

### ISSUE THREAD

**Issue by ghost** [AgoutiGames/RawSalmonEngine#46]
The fastest moving layer should be tall grass and little bushes passing behind the player. 
Typical grass as a good reference to the Outback. Spinifex for example. :smiley_cat:

Trees belong more on layer 2 and 3, which is why we prefer small, dense plants here.

**Specifications:**
_- Look: Spinifex Grass or similar looking._ 
_Dried-up grass and fresh green. Mixed._
_- size: 12000 x 2000 px_
_- format: png_

**Comment by VectorWolf** [comment]
Migrated to https://github.com/AgoutiGames/TerraAustralis/issues
