### ISSUE TITLE
Add parallax background layer 2 (first tree area)

### ISSUE THREAD

**Issue by ghost** [AgoutiGames/RawSalmonEngine#47]
The second fastest layer should be various trees to enhance the impression of depth. 
Different exemplars of the ten most common Australian trees. Acacia, for example, and eucalyptus, of course. This layer runs a little slower, so details are more important. I'd like to see some fun detail. Birds, for example. A Cockatoo here and there... such things. 

**Specifications:**
_- Look: Common Australian trees, in different variations, preferably without much repetitions.
Complemented with cute funny details._
_- Size: 7000 x 1800 px_
_- Format: png_

**Comment by VectorWolf** [comment]
Migrated to https://github.com/AgoutiGames/TerraAustralis/issues
