### ISSUE TITLE
Add parallax background layer 3 (second tree area)

### ISSUE THREAD

**Issue by ghost** [AgoutiGames/RawSalmonEngine#49]
Trees further away are to be drawn on this layer. 
The scroll speed is slower, but the trees are also smaller. 
That's why the details aren't so important.

Basically the same tree types as on layer 2, but smaller. 
Interrupted by grassy plains and sandy areas. 

**Specifications:**
_- Look: Common Australian trees, grassy plains, sand, some rocks and stones._ 
_If possible create an illusion of depth, a view into the far distance._
_- Size: 4500 x 1500 px_
_- Format: png_

**Comment by VectorWolf** [comment]
Migrated to https://github.com/AgoutiGames/TerraAustralis/issues
