### ISSUE TITLE
Add parallax background layer 4 (far distant mountains) 

### ISSUE THREAD

**Issue by ghost** [AgoutiGames/RawSalmonEngine#50]
The slowest layer should be reserved for things on the horizon. Mountains and hills. Everything that makes up the real Australian horizon. Even the sky and a few little happy clouds too.

**Specifications:**
- _Look: Mountains in the far distance, with sky, clouds, some birds drawn in a suggestive way._
- _Size: 3000 x 1300px_
- _Format: png_

**Comment by VectorWolf** [comment]
Migrated to https://github.com/AgoutiGames/TerraAustralis/issues
