### ISSUE TITLE
Proper static UI positioning

### ISSUE THREAD

**Issue by VectorWolf** [AgoutiGames/RawSalmonEngine#65]
The idea on this topic is to implement the UI as an Actor which has its origin set relative to the camera coordinates. This is probably best be done via an Event in its ON_ALWAYS slot, which fetches the camera and repositions the actor by hand.

**Comment by ghost** [comment]
Can't wait for you to put this in. 

![](http://www.publicdomainpictures.net/pictures/60000/nahled/leopard-1378847258UXa.jpg)

**Comment by VectorWolf** [comment]
Added by commits dc1aacb798bdcbdb7050ce4e769a7d8333abc2d8, bb10a15ed65c5d49734873deec64e03301aebec9 and 508e82fe66e2cacdfaea94d6328cbca7b4545e74
