### ISSUE TITLE
Print Strings and numbers to map

### ISSUE THREAD

**Issue by VectorWolf** [AgoutiGames/RawSalmonEngine#68]
At the core this should be no problem since we easily can render text with some font to screen via SDL2. Whats difficult about this job, ist that all actors are based on some kind of Tile. I don't know if its wise trying to stuff such Text objects inside a tile or something. Maybe we have to further develop our Actor class...

**Comment by ghost** [comment]
meow! I like your progress!

**Comment by VectorWolf** [comment]
The current idea is by enhancing the object layers with either a collection or list of so called "primitives". These can be all kinds of (by tiled supported) shapes, text and single tiles. Only function should be to be renderable but they could also be used to store information for events (like camera paths and such).
