### ISSUE TITLE
Write documentation into wiki

### ISSUE THREAD

**Issue by VectorWolf** [AgoutiGames/RawSalmonEngine#70]
Starting the wiki is important! We have to document all possible custom property values and possible quirks so that future users may use the engine without problems.

**Comment by ghost** [comment]
We should think about how we want to implement this... so where we upload/write it and in what way. 
I like the way Blender does it with their wiki.
https://wiki.blender.org/wiki/Main_Page

Not too complex. 
We have enough to do with the projects and their parts. 

But in principle the partitioning would be a nice idea. 
So which components the engine has, which programming languages are used, which modules there are, how it is built and how the style and the code is structured.

Later we can still write such a HowTo. As an introduction and help to make your own little game. 
Just a suggestion.

![](https://get.pxhere.com/photo/wildlife-zoo-mammal-fauna-whiskers-tiger-vertebrate-funny-face-cute-animals-big-cats-funny-animals-tiger-face-cat-like-mammal-tiger-head-tiger-tongue-1226725.jpg)

**Comment by VectorWolf** [comment]
We have a wiki now with the most important points. Well expand on it further with time, adding screenshots, but for the time being it will suffice. https://github.com/AgoutiGames/RawSalmonEngine/wiki
